TestTaskGeekForLess/Models/ErrorViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace TestTaskGeekForLess.Models
{
    [NotMapped]
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestTaskGeekForLess/Models/TreeNode.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace TestTaskGeekForLess.Models
{
    public class TreeNode
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Value { get; set; }
        public int? ParentId { get; set; }
        [NotMapped]
        public List<TreeNode> Children { get; set; }
    }
}

TestTaskGeekForLess/Models/UploadFileWrapper.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace TestTaskGeekForLess.Models
{
    [NotMapped]
    public class UploadFileWrapper
    {
        public IFormFile File { get; set; }
    }
}

TestTaskGeekForLess/Controllers/TreeNodesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using TestTaskGeekForLess.Data;
using TestTaskGeekForLess.Models;
using TestTaskGeekForLess.Utility;

namespace TestTaskGeekForLess.Controllers
{
    [Route("tree")]
    public class TreeNodesController : Controller
    {
        private readonly TestTaskGeekForLessContext _context;
        private ConfigTreeDbManager _treeDbManager;

        private static readonly int PARENT_ID = 1;

        public TreeNodesController(TestTaskGeekForLessContext context)
        {
            _context = context;
            _treeDbManager = new ConfigTreeDbManager(context);
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            TreeNode? rootFromDb = _treeDbManager.RetrieveTree();

            if (rootFromDb == null)
            {
                return RedirectToAction("Create");
            }

            return View(rootFromDb);
        }

        [Route("branch")]
        [HttpGet("branch/{*path}")]
        public IActionResult Branch([FromRoute] string? path = null)
        {
            if (path == null)
            {
                return NotFound();
            }

            string[] paths = path.Split("/");

            TreeNode? parent = new TreeNode()
            {
                Id = PARENT_ID,
            };

            TreeNode? treeNode = new TreeNode();
            for (int i = 0; i < paths.Length; i++)
            {
                try
                {
                    treeNode = _context.TreeNode
                                    .Where(n => n.Name == paths[i] && n.ParentId == parent.Id)
                                    .ToList()
                                    .Single();
                }
                catch (InvalidOperationException e)
                {
                    Debug.WriteLine(e.StackTrace);
                    return NotFound();
                }
                if (treeNode == null)
                {
                    return NotFound();
                }
                parent = treeNode;
            }

            treeNode.Children = _treeDbManager.GetChildren(treeNode);

            return View("Index", treeNode);
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create(UploadFileWrapper formFile)
        {
            TreeNode root;
            if (formFile.File != null && formFile.File.Length > 0)
            {
                _treeDbManager.DeleteTree();
                TreeNodeConverter converter = null;
                if (formFile.File.ContentType == "application/json")
                {
                    converter = new JsonTreeConverter();
                } else if (formFile.File.ContentType == "text/plain")
                {
                    converter = new TxtTreeConverter();
                } else
                {
                    ViewBag.Message = "This format file is not supported";
                    return View("Message");
                }

                root = await _GetRootTreeNodeFromFile(formFile.File, converter);
                _treeDbManager.SaveTree(root);
                await _context.SaveChangesAsync();
            }
            else
            {
                ViewBag.Message = "Please select a JSON file to upload.";

            }

            return View();
        }        
        private async Task<TreeNode> _GetRootTreeNodeFromFile(IFormFile file, TreeNodeConverter converter)
        {
            using (var streamReader = new StreamReader(file.OpenReadStream()))
            {
                var txtContent = await streamReader.ReadToEndAsync();
                
                TreeNode root = converter.convert(txtContent);
                ViewBag.Message = "TXT file uploaded successfully!";

                return root;
            }
        }
    }
}

TestTaskGeekForLess/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTaskGeekForLess</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestTaskGeekForLess.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestTaskGeekForLess</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TreeNodes" asp-action="Index">View Tree</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TreeNodes" asp-action="Create">Create Tree</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TreeNodes" asp-action="Branch">Traverse branches</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestTaskGeekForLess - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TestTaskGeekForLess/Views/TreeConverter/Index.cshtml
@{
    ViewData["Title"] = "TreeConverter";
}

@model FileUploadModel

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <form method="post" asp-action="UploadFile" enctype="multipart/form-data" asp-controller="TreeConverter">
        <div>
            <label asp-for="File">Json file</label>
            <input type="file" asp-for="File" />
        </div>
        <div>
            <button type="submit">Upload File</button>
        </div>
    </form>
</div>

TestTaskGeekForLess/Views/TreeNodes/Create.cshtml
@model UploadFileWrapper

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <form method="post" asp-action="Create" enctype="multipart/form-data" asp-controller="TreeNodes">
        <div>
            <label asp-for="File">Json file</label>
            <input type="file" asp-for="File" />
        </div>
        <div>
            <button type="submit">Upload File</button>
        </div>
    </form>
</div>

TestTaskGeekForLess/Views/TreeNodes/Index.cshtml
@{
    ViewData["Title"] = "Configuration tree";
}

@model TreeNode

<div>
    <h2>Configuration Tree</h2>

    <ul>
        <li>
            @Model.Name: @Model.Value
            @if (Model.Children != null && Model.Children.Any())
            {
                <partial name="_TreeView" model="Model.Children" />
            }
        </li>
    </ul>
</div>

TestTaskGeekForLess/Views/TreeNodes/Message.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Message</title>
</head>
<body>
    <div class="text-center">
        <h1>@ViewBag.Message</h1>
    </div>
</body>
</html>

TestTaskGeekForLess/Views/TreeNodes/_TreeView.cshtml
@model List<TreeNode>

<div>
    <ul>
        @foreach (var child in Model)
        {
            <li>
                @child.Name: @child.Value
                @if (child.Children != null && child.Children.Any())
                {
                    <partial name="_TreeView" model="child.Children" />
                }
            </li>
        }
    </ul>
</div>